/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRoutesRouteRouteImport } from './routes/_protected-routes/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreateUserIndexRouteImport } from './routes/create-user/index'
import { Route as ProtectedRoutesTaskListsIndexRouteImport } from './routes/_protected-routes/task-lists/index'
import { Route as ProtectedRoutesSettingsIndexRouteImport } from './routes/_protected-routes/settings/index'
import { Route as ProtectedRoutesProfileIndexRouteImport } from './routes/_protected-routes/profile/index'
import { Route as ProtectedRoutesPondIndexRouteImport } from './routes/_protected-routes/pond/index'
import { Route as ProtectedRoutesCreateTaskIndexRouteImport } from './routes/_protected-routes/create-task/index'
import { Route as ProtectedRoutesTaskListsTaskListIDRouteImport } from './routes/_protected-routes/task-lists/$taskListID'

const ProtectedRoutesRouteRoute = ProtectedRoutesRouteRouteImport.update({
  id: '/_protected-routes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateUserIndexRoute = CreateUserIndexRouteImport.update({
  id: '/create-user/',
  path: '/create-user/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoutesTaskListsIndexRoute =
  ProtectedRoutesTaskListsIndexRouteImport.update({
    id: '/task-lists/',
    path: '/task-lists/',
    getParentRoute: () => ProtectedRoutesRouteRoute,
  } as any)
const ProtectedRoutesSettingsIndexRoute =
  ProtectedRoutesSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => ProtectedRoutesRouteRoute,
  } as any)
const ProtectedRoutesProfileIndexRoute =
  ProtectedRoutesProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => ProtectedRoutesRouteRoute,
  } as any)
const ProtectedRoutesPondIndexRoute =
  ProtectedRoutesPondIndexRouteImport.update({
    id: '/pond/',
    path: '/pond/',
    getParentRoute: () => ProtectedRoutesRouteRoute,
  } as any)
const ProtectedRoutesCreateTaskIndexRoute =
  ProtectedRoutesCreateTaskIndexRouteImport.update({
    id: '/create-task/',
    path: '/create-task/',
    getParentRoute: () => ProtectedRoutesRouteRoute,
  } as any)
const ProtectedRoutesTaskListsTaskListIDRoute =
  ProtectedRoutesTaskListsTaskListIDRouteImport.update({
    id: '/task-lists/$taskListID',
    path: '/task-lists/$taskListID',
    getParentRoute: () => ProtectedRoutesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-user': typeof CreateUserIndexRoute
  '/task-lists/$taskListID': typeof ProtectedRoutesTaskListsTaskListIDRoute
  '/create-task': typeof ProtectedRoutesCreateTaskIndexRoute
  '/pond': typeof ProtectedRoutesPondIndexRoute
  '/profile': typeof ProtectedRoutesProfileIndexRoute
  '/settings': typeof ProtectedRoutesSettingsIndexRoute
  '/task-lists': typeof ProtectedRoutesTaskListsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-user': typeof CreateUserIndexRoute
  '/task-lists/$taskListID': typeof ProtectedRoutesTaskListsTaskListIDRoute
  '/create-task': typeof ProtectedRoutesCreateTaskIndexRoute
  '/pond': typeof ProtectedRoutesPondIndexRoute
  '/profile': typeof ProtectedRoutesProfileIndexRoute
  '/settings': typeof ProtectedRoutesSettingsIndexRoute
  '/task-lists': typeof ProtectedRoutesTaskListsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected-routes': typeof ProtectedRoutesRouteRouteWithChildren
  '/create-user/': typeof CreateUserIndexRoute
  '/_protected-routes/task-lists/$taskListID': typeof ProtectedRoutesTaskListsTaskListIDRoute
  '/_protected-routes/create-task/': typeof ProtectedRoutesCreateTaskIndexRoute
  '/_protected-routes/pond/': typeof ProtectedRoutesPondIndexRoute
  '/_protected-routes/profile/': typeof ProtectedRoutesProfileIndexRoute
  '/_protected-routes/settings/': typeof ProtectedRoutesSettingsIndexRoute
  '/_protected-routes/task-lists/': typeof ProtectedRoutesTaskListsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-user'
    | '/task-lists/$taskListID'
    | '/create-task'
    | '/pond'
    | '/profile'
    | '/settings'
    | '/task-lists'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-user'
    | '/task-lists/$taskListID'
    | '/create-task'
    | '/pond'
    | '/profile'
    | '/settings'
    | '/task-lists'
  id:
    | '__root__'
    | '/'
    | '/_protected-routes'
    | '/create-user/'
    | '/_protected-routes/task-lists/$taskListID'
    | '/_protected-routes/create-task/'
    | '/_protected-routes/pond/'
    | '/_protected-routes/profile/'
    | '/_protected-routes/settings/'
    | '/_protected-routes/task-lists/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoutesRouteRoute: typeof ProtectedRoutesRouteRouteWithChildren
  CreateUserIndexRoute: typeof CreateUserIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected-routes': {
      id: '/_protected-routes'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRoutesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-user/': {
      id: '/create-user/'
      path: '/create-user'
      fullPath: '/create-user'
      preLoaderRoute: typeof CreateUserIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected-routes/task-lists/': {
      id: '/_protected-routes/task-lists/'
      path: '/task-lists'
      fullPath: '/task-lists'
      preLoaderRoute: typeof ProtectedRoutesTaskListsIndexRouteImport
      parentRoute: typeof ProtectedRoutesRouteRoute
    }
    '/_protected-routes/settings/': {
      id: '/_protected-routes/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedRoutesSettingsIndexRouteImport
      parentRoute: typeof ProtectedRoutesRouteRoute
    }
    '/_protected-routes/profile/': {
      id: '/_protected-routes/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProtectedRoutesProfileIndexRouteImport
      parentRoute: typeof ProtectedRoutesRouteRoute
    }
    '/_protected-routes/pond/': {
      id: '/_protected-routes/pond/'
      path: '/pond'
      fullPath: '/pond'
      preLoaderRoute: typeof ProtectedRoutesPondIndexRouteImport
      parentRoute: typeof ProtectedRoutesRouteRoute
    }
    '/_protected-routes/create-task/': {
      id: '/_protected-routes/create-task/'
      path: '/create-task'
      fullPath: '/create-task'
      preLoaderRoute: typeof ProtectedRoutesCreateTaskIndexRouteImport
      parentRoute: typeof ProtectedRoutesRouteRoute
    }
    '/_protected-routes/task-lists/$taskListID': {
      id: '/_protected-routes/task-lists/$taskListID'
      path: '/task-lists/$taskListID'
      fullPath: '/task-lists/$taskListID'
      preLoaderRoute: typeof ProtectedRoutesTaskListsTaskListIDRouteImport
      parentRoute: typeof ProtectedRoutesRouteRoute
    }
  }
}

interface ProtectedRoutesRouteRouteChildren {
  ProtectedRoutesTaskListsTaskListIDRoute: typeof ProtectedRoutesTaskListsTaskListIDRoute
  ProtectedRoutesCreateTaskIndexRoute: typeof ProtectedRoutesCreateTaskIndexRoute
  ProtectedRoutesPondIndexRoute: typeof ProtectedRoutesPondIndexRoute
  ProtectedRoutesProfileIndexRoute: typeof ProtectedRoutesProfileIndexRoute
  ProtectedRoutesSettingsIndexRoute: typeof ProtectedRoutesSettingsIndexRoute
  ProtectedRoutesTaskListsIndexRoute: typeof ProtectedRoutesTaskListsIndexRoute
}

const ProtectedRoutesRouteRouteChildren: ProtectedRoutesRouteRouteChildren = {
  ProtectedRoutesTaskListsTaskListIDRoute:
    ProtectedRoutesTaskListsTaskListIDRoute,
  ProtectedRoutesCreateTaskIndexRoute: ProtectedRoutesCreateTaskIndexRoute,
  ProtectedRoutesPondIndexRoute: ProtectedRoutesPondIndexRoute,
  ProtectedRoutesProfileIndexRoute: ProtectedRoutesProfileIndexRoute,
  ProtectedRoutesSettingsIndexRoute: ProtectedRoutesSettingsIndexRoute,
  ProtectedRoutesTaskListsIndexRoute: ProtectedRoutesTaskListsIndexRoute,
}

const ProtectedRoutesRouteRouteWithChildren =
  ProtectedRoutesRouteRoute._addFileChildren(ProtectedRoutesRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoutesRouteRoute: ProtectedRoutesRouteRouteWithChildren,
  CreateUserIndexRoute: CreateUserIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
